--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/klownie/Pictures/airi-pan-bunny-gold-airipan-small.jpg"

-- Special
background="#0c0903"
foreground="#dac0a6"
cursor="#dac0a6"

-- Colors
color0="#0c0903"
color1="#72482C"
color2="#973720"
color3="#925736"
color4="#996647"
color5="#97684C"
color6="#AD7451"
color7="#dac0a6"
color8="#988674"
color9="#72482C"
color10="#973720"
color11="#925736"
color12="#996647"
color13="#97684C"
color14="#AD7451"
color15="#dac0a6"
