# Shell variables
# Generated by 'wal'
wallpaper='/home/klownie/Pictures/airi-pan-bunny-gold-airipan-small.jpg'

# Special
background='#0c0903'
foreground='#dac0a6'
cursor='#dac0a6'

# Colors
color0='#0c0903'
color1='#72482C'
color2='#973720'
color3='#925736'
color4='#996647'
color5='#97684C'
color6='#AD7451'
color7='#dac0a6'
color8='#988674'
color9='#72482C'
color10='#973720'
color11='#925736'
color12='#996647'
color13='#97684C'
color14='#AD7451'
color15='#dac0a6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
